export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import 'src/styles/globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <div className="container h-screen flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
